// Dummy JSON data for OfferHub
const OFFERHUB_PRODUCTS = [

{id:1,name:"boAt Airdopes 141 True Wireless Earbuds",price:1199,discount:40,platform:"Amazon",platform_url:"https://amazon.in/product/1",category:"Electronics",image_url:"https://picsum.photos/seed/product-1/520/320"},
{id:2,name:"Noise ColorFit Pulse Smartwatch",price:1499,discount:55,platform:"Flipkart",platform_url:"https://flipkart.com/product/2",category:"Wearables",image_url:"https://picsum.photos/seed/product-2/520/320"},
{id:3,name:"Samsung Galaxy M34 5G",price:15999,discount:22,platform:"Amazon",platform_url:"https://amazon.in/product/3",category:"Mobiles",image_url:"https://picsum.photos/seed/product-3/520/320"},
{id:4,name:"OnePlus Nord CE 3 Lite",price:17999,discount:18,platform:"Amazon",platform_url:"https://amazon.in/product/4",category:"Mobiles",image_url:"https://picsum.photos/seed/product-4/520/320"},
{id:5,name:"Apple AirPods Pro (2nd Gen)",price:23899,discount:12,platform:"Amazon",platform_url:"https://amazon.in/product/5",category:"Electronics",image_url:"https://picsum.photos/seed/product-5/520/320"},
{id:6,name:"Puma Men’s Running Shoes",price:2299,discount:63,platform:"Flipkart",platform_url:"https://flipkart.com/product/6",category:"Fashion",image_url:"https://picsum.photos/seed/product-6/520/320"},
{id:7,name:"Boat Rockerz 255 Pro+",price:999,discount:60,platform:"Amazon",platform_url:"https://amazon.in/product/7",category:"Electronics",image_url:"https://picsum.photos/seed/product-7/520/320"},
{id:8,name:"Mi 10000mAh Power Bank 3i",price:899,discount:40,platform:"Amazon",platform_url:"https://amazon.in/product/8",category:"Accessories",image_url:"https://picsum.photos/seed/product-8/520/320"},
{id:9,name:"HP Ink Tank 316 Printer",price:10499,discount:25,platform:"Flipkart",platform_url:"https://flipkart.com/product/9",category:"Electronics",image_url:"https://picsum.photos/seed/product-9/520/320"},
{id:10,name:"Lenovo IdeaPad Slim 3 Laptop",price:32999,discount:28,platform:"Amazon",platform_url:"https://amazon.in/product/10",category:"Laptops",image_url:"https://picsum.photos/seed/product-10/520/320"},

{id:11,name:"Realme Buds Wireless 3",price:999,discount:50,platform:"Flipkart",platform_url:"https://flipkart.com/product/11",category:"Electronics",image_url:"https://picsum.photos/seed/product-11/520/320"},
{id:12,name:"Xiaomi Trimmer 2C",price:799,discount:30,platform:"Amazon",platform_url:"https://amazon.in/product/12",category:"Personal Care",image_url:"https://picsum.photos/seed/product-12/520/320"},
{id:13,name:"Philips Hair Dryer 1200W",price:849,discount:35,platform:"Amazon",platform_url:"https://amazon.in/product/13",category:"Personal Care",image_url:"https://picsum.photos/seed/product-13/520/320"},
{id:14,name:"Prestige Electric Kettle 1.5L",price:699,discount:45,platform:"Amazon",platform_url:"https://amazon.in/product/14",category:"Home Appliances",image_url:"https://picsum.photos/seed/product-14/520/320"},
{id:15,name:"Nivia Gym Gloves",price:299,discount:25,platform:"Amazon",platform_url:"https://amazon.in/product/15",category:"Fitness",image_url:"https://picsum.photos/seed/product-15/520/320"},
{id:16,name:"Urbano Fashion Slim Jeans",price:899,discount:60,platform:"Flipkart",platform_url:"https://flipkart.com/product/16",category:"Fashion",image_url:"https://picsum.photos/seed/product-16/520/320"},
{id:17,name:"Redgear A-20 Gaming Mouse",price:499,discount:50,platform:"Amazon",platform_url:"https://amazon.in/product/17",category:"Gaming",image_url:"https://picsum.photos/seed/product-17/520/320"},
{id:18,name:"Logitech MK215 Wireless Keyboard Mouse Combo",price:1399,discount:30,platform:"Amazon",platform_url:"https://amazon.in/product/18",category:"Computers",image_url:"https://picsum.photos/seed/product-18/520/320"},
{id:19,name:"SanDisk 128GB Pendrive USB 3.2",price:799,discount:55,platform:"Flipkart",platform_url:"https://flipkart.com/product/19",category:"Accessories",image_url:"https://picsum.photos/seed/product-19/520/320"},
{id:20,name:"Canon EOS 1500D DSLR Camera",price:38999,discount:15,platform:"Amazon",platform_url:"https://amazon.in/product/20",category:"Cameras",image_url:"https://picsum.photos/seed/product-20/520/320"},

{id:21,name:"WildHorn Leather Wallet",price:499,discount:62,platform:"Amazon",platform_url:"https://amazon.in/product/21",category:"Fashion",image_url:"https://picsum.photos/seed/product-21/520/320"},
{id:22,name:"Skybags Casual Backpack",price:899,discount:55,platform:"Amazon",platform_url:"https://amazon.in/product/22",category:"Bags",image_url:"https://picsum.photos/seed/product-22/520/320"},
{id:23,name:"JBL Tune 760NC Headphones",price:6499,discount:20,platform:"Flipkart",platform_url:"https://flipkart.com/product/23",category:"Electronics",image_url:"https://picsum.photos/seed/product-23/520/320"},
{id:24,name:"Samsung 27-inch Curved Monitor",price:15999,discount:30,platform:"Amazon",platform_url:"https://amazon.in/product/24",category:"Computers",image_url:"https://picsum.photos/seed/product-24/520/320"},
{id:25,name:"Boat Stone 350 Bluetooth Speaker",price:1599,discount:45,platform:"Amazon",platform_url:"https://amazon.in/product/25",category:"Electronics",image_url:"https://picsum.photos/seed/product-25/520/320"},
{id:26,name:"Lifelong LLDC27 Cycle",price:4999,discount:35,platform:"Flipkart",platform_url:"https://flipkart.com/product/26",category:"Fitness",image_url:"https://picsum.photos/seed/product-26/520/320"},
{id:27,name:"Acer Nitro 5 Gaming Laptop",price:72999,discount:18,platform:"Amazon",platform_url:"https://amazon.in/product/27",category:"Laptops",image_url:"https://picsum.photos/seed/product-27/520/320"},
{id:28,name:"HP M100 Wired Mouse",price:299,discount:40,platform:"Amazon",platform_url:"https://amazon.in/product/28",category:"Computers",image_url:"https://picsum.photos/seed/product-28/520/320"},
{id:29,name:"Fossil FS4545 Men's Watch",price:7499,discount:35,platform:"Amazon",platform_url:"https://amazon.in/product/29",category:"Fashion",image_url:"https://picsum.photos/seed/product-29/520/320"},
{id:30,name:"Adidas Men’s Slides",price:699,discount:45,platform:"Flipkart",platform_url:"https://flipkart.com/product/30",category:"Fashion",image_url:"https://picsum.photos/seed/product-30/520/320"},

{id:31,name:"Vega Helmet Cruiser",price:899,discount:25,platform:"Amazon",platform_url:"https://amazon.in/product/31",category:"Automobile",image_url:"https://picsum.photos/seed/product-31/520/320"},
{id:32,name:"Colgate Electric Toothbrush",price:949,discount:20,platform:"Amazon",platform_url:"https://amazon.in/product/32",category:"Personal Care",image_url:"https://picsum.photos/seed/product-32/520/320"},
{id:33,name:"Beardo Beard Oil",price:249,discount:30,platform:"Flipkart",platform_url:"https://flipkart.com/product/33",category:"Grooming",image_url:"https://picsum.photos/seed/product-33/520/320"},
{id:34,name:"Mamaearth Ubtan Face Wash",price:249,discount:25,platform:"Amazon",platform_url:"https://amazon.in/product/34",category:"Beauty",image_url:"https://picsum.photos/seed/product-34/520/320"},
{id:35,name:"Urban Terrain UT100 Cycle",price:6999,discount:40,platform:"Amazon",platform_url:"https://amazon.in/product/35",category:"Fitness",image_url:"https://picsum.photos/seed/product-35/520/320"},
{id:36,name:"Lifelong Yoga Mat 6mm",price:449,discount:50,platform:"Amazon",platform_url:"https://amazon.in/product/36",category:"Fitness",image_url:"https://picsum.photos/seed/product-36/520/320"},
{id:37,name:"Fire-Boltt Phoenix Smartwatch",price:1299,discount:65,platform:"Amazon",platform_url:"https://amazon.in/product/37",category:"Wearables",image_url:"https://picsum.photos/seed/product-37/520/320"},
{id:38,name:"Dell 15-inch Laptop Backpack",price:899,discount:55,platform:"Amazon",platform_url:"https://amazon.in/product/38",category:"Bags",image_url:"https://picsum.photos/seed/product-38/520/320"},
{id:39,name:"AmazonBasics USB-C Cable 1m",price:299,discount:50,platform:"Amazon",platform_url:"https://amazon.in/product/39",category:"Accessories",image_url:"https://picsum.photos/seed/product-39/520/320"},
{id:40,name:"Mi Home Security Camera 360°",price:2899,discount:28,platform:"Flipkart",platform_url:"https://flipkart.com/product/40",category:"Home Appliances",image_url:"https://picsum.photos/seed/product-40/520/320"},

{id:41,name:"Philips Trimmer BT3102",price:999,discount:35,platform:"Amazon",platform_url:"https://amazon.in/product/41",category:"Personal Care",image_url:"https://picsum.photos/seed/product-41/520/320"},
{id:42,name:"Nova Hair Straightener",price:649,discount:45,platform:"Amazon",platform_url:"https://amazon.in/product/42",category:"Personal Care",image_url:"https://picsum.photos/seed/product-42/520/320"},
{id:43,name:"Zebronics Wired Keyboard",price:349,discount:30,platform:"Amazon",platform_url:"https://amazon.in/product/43",category:"Computers",image_url:"https://picsum.photos/seed/product-43/520/320"},
{id:44,name:"Boult Audio Z40 Earbuds",price:1099,discount:60,platform:"Flipkart",platform_url:"https://flipkart.com/product/44",category:"Electronics",image_url:"https://picsum.photos/seed/product-44/520/320"},
{id:45,name:"American Tourister Suitcase 55cm",price:2799,discount:55,platform:"Amazon",platform_url:"https://amazon.in/product/45",category:"Bags",image_url:"https://picsum.photos/seed/product-45/520/320"},
{id:46,name:"Solimo Bedsheet Queen Size",price:499,discount:45,platform:"Amazon",platform_url:"https://amazon.in/product/46",category:"Home",image_url:"https://picsum.photos/seed/product-46/520/320"},
{id:47,name:"Havells 1200mm Ceiling Fan",price:1599,discount:30,platform:"Flipkart",platform_url:"https://flipkart.com/product/47",category:"Home Appliances",image_url:"https://picsum.photos/seed/product-47/520/320"},
{id:48,name:"Usha Mixer Grinder 750W",price:2999,discount:35,platform:"Amazon",platform_url:"https://amazon.in/product/48",category:"Kitchen",image_url:"https://picsum.photos/seed/product-48/520/320"},
{id:49,name:"Prestige Gas Stove 2 Burner",price:3299,discount:20,platform:"Amazon",platform_url:"https://amazon.in/product/49",category:"Kitchen",image_url:"https://picsum.photos/seed/product-49/520/320"},
{id:50,name:"Milton Thermosteel Bottle 1L",price:699,discount:45,platform:"Amazon",platform_url:"https://amazon.in/product/50",category:"Home",image_url:"https://picsum.photos/seed/product-50/520/320"},

{id:51,name:"Boat Wave Call Smartwatch",price:1499,discount:70,platform:"Amazon",platform_url:"https://amazon.in/product/51",category:"Wearables",image_url:"https://picsum.photos/seed/product-51/520/320"},
{id:52,name:"Sony WH-CH520 Bluetooth Headphones",price:4499,discount:20,platform:"Amazon",platform_url:"https://amazon.in/product/52",category:"Electronics",image_url:"https://picsum.photos/seed/product-52/520/320"},
{id:53,name:"Echo Dot 5th Gen Smart Speaker",price:4499,discount:25,platform:"Amazon",platform_url:"https://amazon.in/product/53",category:"Home Appliances",image_url:"https://picsum.photos/seed/product-53/520/320"},
{id:54,name:"Philips GC1905 Iron",price:1199,discount:25,platform:"Flipkart",platform_url:"https://flipkart.com/product/54",category:"Home Appliances",image_url:"https://picsum.photos/seed/product-54/520/320"},
{id:55,name:"Samsung Galaxy Watch 4",price:11999,discount:40,platform:"Amazon",platform_url:"https://amazon.in/product/55",category:"Wearables",image_url:"https://picsum.photos/seed/product-55/520/320"},
{id:56,name:"Lenskart Blu Cut Glasses",price:799,discount:60,platform:"Lenskart",platform_url:"https://lenskart.com/product/56",category:"Fashion",image_url:"https://picsum.photos/seed/product-56/520/320"},
{id:57,name:"Campus Men’s Sneakers",price:799,discount:55,platform:"Flipkart",platform_url:"https://flipkart.com/product/57",category:"Fashion",image_url:"https://picsum.photos/seed/product-57/520/320"},
{id:58,name:"Lenovo Tab M10 HD",price:8999,discount:22,platform:"Amazon",platform_url:"https://amazon.in/product/58",category:"Tablets",image_url:"https://picsum.photos/seed/product-58/520/320"},
{id:59,name:"Sony Alpha A6400 Mirrorless Camera",price:84999,discount:10,platform:"Amazon",platform_url:"https://amazon.in/product/59",category:"Cameras",image_url:"https://picsum.photos/seed/product-59/520/320"},
{id:60,name:"Realme Smart TV 43-inch",price:22999,discount:18,platform:"Flipkart",platform_url:"https://flipkart.com/product/60",category:"TV",image_url:"https://picsum.photos/seed/product-60/520/320"},

{id:61,name:"LG Refrigerator 190L",price:15999,discount:20,platform:"Amazon",platform_url:"https://amazon.in/product/61",category:"Appliances",image_url:"https://picsum.photos/seed/product-61/520/320"},
{id:62,name:"Whirlpool Washing Machine 7kg",price:13999,discount:25,platform:"Flipkart",platform_url:"https://flipkart.com/product/62",category:"Appliances",image_url:"https://picsum.photos/seed/product-62/520/320"},
{id:63,name:"Dyson V8 Vacuum Cleaner",price:29999,discount:10,platform:"Amazon",platform_url:"https://amazon.in/product/63",category:"Home Appliances",image_url:"https://picsum.photos/seed/product-63/520/320"},
{id:64,name:"Canon G2012 Printer",price:13499,discount:18,platform:"Amazon",platform_url:"https://amazon.in/product/64",category:"Electronics",image_url:"https://picsum.photos/seed/product-64/520/320"},
{id:65,name:"Apple Watch Series 9",price:41999,discount:8,platform:"Amazon",platform_url:"https://amazon.in/product/65",category:"Wearables",image_url:"https://picsum.photos/seed/product-65/520/320"},
{id:66,name:"Beats Studio Buds",price:14999,discount:25,platform:"Amazon",platform_url:"https://amazon.in/product/66",category:"Electronics",image_url:"https://picsum.photos/seed/product-66/520/320"},
{id:67,name:"Mi Portable Bluetooth Speaker",price:1999,discount:40,platform:"Flipkart",platform_url:"https://flipkart.com/product/67",category:"Electronics",image_url:"https://picsum.photos/seed/product-67/520/320"},
{id:68,name:"Jockey Men’s Boxers Pack of 2",price:549,discount:25,platform:"Amazon",platform_url:"https://amazon.in/product/68",category:"Fashion",image_url:"https://picsum.photos/seed/product-68/520/320"},
{id:69,name:"Pigeon Chopper Pro XL",price:399,discount:45,platform:"Amazon",platform_url:"https://amazon.in/product/69",category:"Kitchen",image_url:"https://picsum.photos/seed/product-69/520/320"},
{id:70,name:"Tata Coffee Quick Filter",price:299,discount:20,platform:"Amazon",platform_url:"https://amazon.in/product/70",category:"Grocery",image_url:"https://picsum.photos/seed/product-70/520/320"},

{id:71,name:"Garnier Men Face Wash",price:199,discount:25,platform:"Flipkart",platform_url:"https://flipkart.com/product/71",category:"Beauty",image_url:"https://picsum.photos/seed/product-71/520/320"},
{id:72,name:"Swiss Beauty Eyeshadow Palette",price:249,discount:35,platform:"Amazon",platform_url:"https://amazon.in/product/72",category:"Beauty",image_url:"https://picsum.photos/seed/product-72/520/320"},
{id:73,name:"Aroma Electric Room Heater",price:1299,discount:40,platform:"Amazon",platform_url:"https://amazon.in/product/73",category:"Home Appliances",image_url:"https://picsum.photos/seed/product-73/520/320"},
{id:74,name:"Philips LED Bulb 12W",price:149,discount:25,platform:"Flipkart",platform_url:"https://flipkart.com/product/74",category:"Home",image_url:"https://picsum.photos/seed/product-74/520/320"},
{id:75,name:"Borosil Lunch Box Set",price:999,discount:35,platform:"Amazon",platform_url:"https://amazon.in/product/75",category:"Kitchen",image_url:"https://picsum.photos/seed/product-75/520/320"},
{id:76,name:"Balzano Hand Blender 500W",price:899,discount:45,platform:"Amazon",platform_url:"https://amazon.in/product/76",category:"Kitchen",image_url:"https://picsum.photos/seed/product-76/520/320"},
{id:77,name:"Skybags Trolley Bag 65L",price:3199,discount:50,platform:"Flipkart",platform_url:"https://flipkart.com/product/77",category:"Bags",image_url:"https://picsum.photos/seed/product-77/520/320"},
{id:78,name:"Casio Scientific Calculator",price:699,discount:15,platform:"Amazon",platform_url:"https://amazon.in/product/78",category:"Education",image_url:"https://picsum.photos/seed/product-78/520/320"},
{id:79,name:"Dettol Handwash 1L",price:129,discount:10,platform:"Amazon",platform_url:"https://amazon.in/product/79",category:"Grocery",image_url:"https://picsum.photos/seed/product-79/520/320"},
{id:80,name:"Surf Excel Matic 2kg",price:349,discount:20,platform:"Flipkart",platform_url:"https://flipkart.com/product/80",category:"Grocery",image_url:"https://picsum.photos/seed/product-80/520/320"},

{id:81,name:"boAt Bassheads 103 Wired Earphones",price:349,discount:30,platform:"Amazon",platform_url:"https://amazon.in/product/81",category:"Electronics",image_url:"https://picsum.photos/seed/product-81/520/320"},
{id:82,name:"Samsung Galaxy S24 Ultra",price:119999,discount:5,platform:"Amazon",platform_url:"https://amazon.in/product/82",category:"Mobiles",image_url:"https://picsum.photos/seed/product-82/520/320"},
{id:83,name:"OnePlus Buds Z2",price:3999,discount:20,platform:"Amazon",platform_url:"https://amazon.in/product/83",category:"Electronics",image_url:"https://picsum.photos/seed/product-83/520/320"},
{id:84,name:"MSI GF63 Gaming Laptop",price:54999,discount:18,platform:"Flipkart",platform_url:"https://flipkart.com/product/84",category:"Laptops",image_url:"https://picsum.photos/seed/product-84/520/320"},
{id:85,name:"Amazfit Bip 3 Smartwatch",price:2499,discount:35,platform:"Amazon",platform_url:"https://amazon.in/product/85",category:"Wearables",image_url:"https://picsum.photos/seed/product-85/520/320"},
{id:86,name:"Nike Men’s Sports T-shirt",price:1199,discount:40,platform:"Nike",platform_url:"https://nike.com/product/86",category:"Fashion",image_url:"https://picsum.photos/seed/product-86/520/320"},
{id:87,name:"Reebok Training Shorts",price:799,discount:50,platform:"Amazon",platform_url:"https://amazon.in/product/87",category:"Fashion",image_url:"https://picsum.photos/seed/product-87/520/320"},
{id:88,name:"Poco X6 Pro 5G",price:24999,discount:10,platform:"Flipkart",platform_url:"https://flipkart.com/product/88",category:"Mobiles",image_url:"httpsum.photos/seed/product-88/520/320"},
{id:89,name:"Insta360 GO 3 Action Camera",price:29999,discount:12,platform:"Amazon",platform_url:"https://amazon.in/product/89",category:"Cameras",image_url:"https://picsum.photos/seed/product-89/520/320"},
{id:90,name:"JBL Partybox 110 Speaker",price:29999,discount:20,platform:"Amazon",platform_url:"https://amazon.in/product/90",category:"Electronics",image_url:"https://picsum.photos/seed/product-90/520/320"},

{id:91,name:"TWS M80 Gaming Earbuds",price:999,discount:60,platform:"Meesho",platform_url:"https://meesho.com/product/91",category:"Electronics",image_url:"https://picsum.photos/seed/product-91/520/320"},
{id:92,name:"Trendy Women Kurti Set",price:499,discount:70,platform:"Meesho",platform_url:"https://meesho.com/product/92",category:"Fashion",image_url:"https://picsum.photos/seed/product-92/520/320"},
{id:93,name:"Stainless Steel Water Bottle 2L",price:349,discount:55,platform:"Meesho",platform_url:"https://meesho.com/product/93",category:"Home",image_url:"https://picsum.photos/seed/product-93/520/320"},
{id:94,name:"Cotton Bedsheet Set",price:399,discount:50,platform:"Meesho",platform_url:"https://meesho.com/product/94",category:"Home",image_url:"https://picsum.photos/seed/product-94/520/320"},
{id:95,name:"Kids Printed T-shirt Pack of 3",price:299,discount:60,platform:"Meesho",platform_url:"https://meesho.com/product/95",category:"Kids",image_url:"https://picsum.photos/seed/product-95/520/320"},
{id:96,name:"Fashion Alloy Earrings",price:199,discount:65,platform:"Meesho",platform_url:"https://meesho.com/product/96",category:"Fashion",image_url:"https://picsum.photos/seed/product-96/520/320"},
{id:97,name:"Makeup Brush Set 12pcs",price:259,discount:70,platform:"Meesho",platform_url:"https://meesho.com/product/97",category:"Beauty",image_url:"https://picsum.photos/seed/product-97/520/320"},
{id:98,name:"Wireless Neckband Sports Edition",price:549,discount:50,platform:"Meesho",platform_url:"https://meesho.com/product/98",category:"Electronics",image_url:"https://picsum.photos/seed/product-98/520/320"},
{id:99,name:"Men’s Stylish Analog Watch",price:349,discount:75,platform:"Meesho",platform_url:"https://meesho.com/product/99",category:"Fashion",image_url:"https://picsum.photos/seed/product-99/520/320"},
{id:100,name:"Women’s Handbag Combo Set",price:449,discount:65,platform:"Meesho",platform_url:"https://meesho.com/product/100",category:"Fashion",image_url:"https://picsum.photos/seed/product-100/520/320"},
{id:111,name:"Sony WH-1000XM4 Wireless Headphones",price:19800,discount:26,platform:"Amazon",platform_url:"https://amazon.example.com/product/1",category:"Electronics",image_url:"https://picsum.photos/seed/product-1/520/320"},
{id:112,name:"OnePlus 9R 5G",price:35999,discount:25,platform:"Flipkart",platform_url:"https://flipkart.example.com/product/2",category:"Mobiles",image_url:"https://picsum.photos/seed/product-2/520/320"},
{id:113,name:"Levis Men's Jeans",price:2299,discount:40,platform:"Myntra",platform_url:"https://myntra.example.com/product/3",category:"Apparel",image_url:"https://picsum.photos/seed/product-3/520/320"},
{id:114,name:"Nike Running Shoes",price:6599,discount:15,platform:"Ajio",platform_url:"https://ajio.example.com/product/4",category:"Footwear",image_url:"https://picsum.photos/seed/product-4/520/320"},
{id:115,name:'Samsung 55" 4K Smart TV',price:49990,discount:20,platform:'Amazon',platform_url:'https://amazon.example.com/product/5',category:'Electronics',image_url:'https://picsum.photos/seed/product-5/520/320'},
{id:116,name:"HP Pavilion Laptop",price:45990,discount:10,platform:"Flipkart",platform_url:"https://flipkart.example.com/product/6",category:"Computers",image_url:"https://picsum.photos/seed/product-6/520/320"},
{id:117,name:"Ray-Ban Sunglasses",price:7399,discount:35,platform:"Myntra",platform_url:"https://myntra.example.com/product/7",category:"Accessories",image_url:"https://picsum.photos/seed/product-7/520/320"},
{id:118,name:"Garnier Facewash",price:149,discount:33,platform:"Amazon",platform_url:"https://amazon.example.com/product/8",category:"Beauty",image_url:"https://picsum.photos/seed/product-8/520/320"},
{id:119,name:"KitchenAid Mixer",price:35999,discount:12,platform:"Amazon",platform_url:"https://amazon.example.com/product/9",category:"Home",image_url:"https://picsum.photos/seed/product-9/520/320"},
{id:101,name:"Samsung Galaxy Buds",price:7999,discount:18,platform:"Flipkart",platform_url:"https://flipkart.example.com/product/10",category:"Electronics",image_url:"https://picsum.photos/seed/product-10/520/320"},
{id:101,name:"Zara Dress for Women",price:3999,discount:30,platform:"Ajio",platform_url:"https://ajio.example.com/product/11",category:"Apparel",image_url:"https://picsum.photos/seed/product-11/520/320"},
{id:102,name:"Ultima Water Bottle",price:999,discount:5,platform:"Amazon",platform_url:"https://amazon.example.com/product/12",category:"Home",image_url:"https://picsum.photos/seed/product-12/520/320"},
{id:103,name:"Ultima Water Bottle",price:999,discount:5,platform:"Amazon",platform_url:"https://amazon.example.com/product/12",category:"Home",image_url:"https://picsum.photos/seed/product-12/520/320"}

];

// Pre-populate with a sample coupon
const OFFERHUB_COUPONS_DEFAULT = [
  {id:1,platform:'Flipkart',category:'Electronics',description:'20% off on mobile accessories',price:50,code:'FLIP20OFF',revealed:false,sellerPhone:'9876543210'},
  {id:2,platform:'Amazon',category:'Apparel',description:'25% off on select apparel',price:30,code:'AMZ25APP',revealed:false,sellerPhone:'9123456780'},
  {id:3,platform:'Amazon',category:'Skincare',description:'55% off on select apparel',price:30,code:'AMZ25APP',revealed:false,sellerPhone:'9123856780'}

];
